#!/usr/bin/with-contenv bash

# create symlinks
symlinks=( \
/var/www/html/config.php \
/var/www/html/themes.local \
/var/www/html/plugins.local \
/var/www/html/cache \
/var/www/html/lock \
/var/www/html/feed-icons
)

for i in "${symlinks[@]}"; do
	[[ "$(basename "$i")" == "config.php" && ! -L "$i" ]] && \
		ln -s /config/"$(basename "$i")" "$i"
	[[ -e "$i" && ! -L "$i" && -e /config/"$(basename "$i")" ]] && \
		rm -Rf "$i" && \
		ln -s /config/"$(basename "$i")" "$i"
	[[ -e "$i" && ! -L "$i" ]] && \
		mv "$i" /config/"$(basename "$i")" && \
		ln -s /config/"$(basename "$i")" "$i"
done

# permissions
chown -R abc:abc \
	/config \
	/var/www/html/
